-- Create the users table
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    email character varying,
    password character varying DEFAULT ''::character varying,
    username character varying,
    user_colour character varying,
    "likedTweets" json,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- Insert data into the users table
INSERT INTO public.users (email, password, username, user_colour, "likedTweets")
VALUES
  ('corey@gmail.com', 'GGG', 'Corey123', 'text-purple-500', '["24680", "13579"]'::json),
  ('alice@gmail.com', 'AAA', 'Alice123', 'text-twitterBlue', '["24680"]'::json),
  ('bob@gmail.com', 'BBB', 'Bob456', 'text-twitterBlue', '[]'::json),
  ('david@gmail.com', 'DDD', 'David789', 'text-twitterBlue', '[]'::json);
